config/routes.rb
Bill::Application.routes.draw do
  root :to => 'invoices#index'

  resources :invoices do
    member do
      end
      collection do
        match 'change'
        get 'additem'
      end
    end
    resources :products
    resources :line_items

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  has_many :line_items , :dependent => :destroy, :autosave => true

  accepts_nested_attributes_for :line_items , :reject_if => lambda { |a| (a[:quantity].blank? || a[:description].blank? ) }, :allow_destroy => true
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :invoice
  attr_accessible :quantity ,:invoice_id, :product_id, :description, :unitprice, :amount, :tax, :total_amount
  
end

app/models/product.rb
class Product < ActiveRecord::Base

  attr_accessible :name, :description, :price

  validates :name,  :presence => { :message => "Product name is required" }
  validates :name, :uniqueness => { :case_sensitive => false }
  validates :description,  :presence => { :message => "Description is required" }
  validates :price, :presence => { :message => "Price is required" }
  validates :price, :numericality => { :message => "Please enter only Decimal number" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    @invoices = Invoice.all
  end
  # new invoice
  def new
    @invoice = Invoice.new
    5.times{ @invoice.line_items.build }
  end
  # create invoice
  def create
    puts "=================================#{params[:invoice]}"
    @invoice = Invoice.new(params[:invoice])
    if @invoice.save
      flash[:notice] = "Successfully Invoice Created"
      redirect_to root_url
    else
      render "new"
    end
  end
  # edit invoice
  def edit
    @invoice = Invoice.find(params[:id])
  end
  # update invoice
  def update
    puts "=======================#{params[:invoice][:line_items_attributes]}"
    @invoice = Invoice.find(params[:id])
    if @invoice.update_attributes(params[:invoice])
      flash[:notice] = "Successfully Invoice Edited"
      redirect_to root_url
    else
      render :action => 'edit'
    end
  end
  # delete invoice
  def destroy
    @invoice = Invoice.find(params[:id])
    if @invoice.destroy
      flash[:notice] = "Successfully Invoice Deleted"
      redirect_to root_url
    end
  end

  def change
    if !params[:id].blank?
      @products = Product.find(params[:id])
      puts "==============#{params[:id]}"
      render :text => @products.to_json
    else
      render :text => ""
    end
  end

  def show
    @invoice = Invoice.find(params[:id])
    puts "==========================#{@invoice}"
    render :layout => false
  end

 
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  #new products
  def new
    @product = Product.new
  end
  #create products
  def create
    @product = Product.new(params[:product])
    if @product.valid?
      @product.save
      flash[:notice] = "Successfully Product Created"
      redirect_to root_url
    else
      render "new"
    end
  end
  #edit products
  def edit
    @product = Product.find(params[:id])
  end
  #update products
  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(params[:product])
      flash[:notice] = "Successfully Product Edited"
      redirect_to root_url
    else
      render :action => 'edit'
    end
  end

  def show
    puts "==========================================product destroy"
  end
  #delete products
  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:notice] = "Successfully Product Deleted"
      redirect_to root_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, ("add_fields(this, '#{association}', '#{escape_javascript(fields.html_safe)}')"))
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/invoices/_line_item_fields.html.erb
<% randid = rand(999999) %>
<tr class="fields" id="line" style="border: 1px solid #999;">
  <td style="border: 1px solid #999;"><%= f.select :product_id , Product.all.collect{|p| [p.name, p.id]}, {:prompt => 'Select Product'} ,:class => 'citem',:id => "prod-#{randid}" %></td>
  <td style="border: 1px solid #999;"><%= f.text_field :description,:size => 30 , :id => "desc-#{randid}" ,:readonly => "readonly"%></td>
  <td style="border: 1px solid #999;"><%= f.text_field :quantity, :size => 2 ,:class => "qntity" ,:id => "qnty-#{randid}"%></td>
  <td style="border: 1px solid #999;"><%= f.text_field :unitprice,:size => 4 ,  :id => "upri-#{randid}" ,:readonly => "readonly"%></td>
  <td style="border: 1px solid #999;"><%= f.text_field :amount ,:size => 6 ,  :id => "amount-#{randid}" ,:readonly => "readonly"%></td>
  <td style="border: 1px solid #999;"><%= f.text_field  :tax ,:size => 4 ,:id => "tax-#{randid}" ,:readonly => "readonly"%></td>
  <td style="border: 1px solid #999;"><%= f.text_field :total_amount ,:size => 6,  :id => "toamount-#{randid}" ,:class => "total_amount",:readonly => "readonly" %></td>
  <td style="border: 1px solid #999;"><%= f.hidden_field :_destroy %> <%= link_to_function "Remove", "remove_fields(this,#{randid})" %></td>
</tr>

<!--<%# if params[:action] != 'edit' %>-->

app/views/invoices/edit.html.erb
<div><br></br></div>
<div>
  <%= form_for(@invoice, :url => invoice_path(:id => @invoice.id) ,:method => 'PUT') do |f| %>
    <div style="float: left; padding-left: 10px;"><b>Date: </b><%= @invoice.created_at.strftime("%m/%d/%Y")%></div>
    <div style="float: left; padding-left: 50px;"><b>Due Date: </b><%= f.text_field :due_date, :id => "datepicker2"%></div>
    <div style="float: left; padding-left: 50px;"><b>Invoice #</b> INV-<%= @invoice.id %></div>
    <div style="padding: 10px 0 20px 0;"><br></br></div>
    <table class="imagetable" style="width:auto;">
      <th style="border: 1px solid #999"> Item </th>
      <th style="border: 1px solid #999"> Description </th>
      <th style="border: 1px solid #999"> Qty </th>
      <th style="border: 1px solid #999"> Unit Price </th>
      <th style="border: 1px solid #999"> Amount </th>
      <th style="border: 1px solid #999"> Tax Rate </th>
      <th style="border: 1px solid #999"> Amount USD </th>
      <th style="border: 1px solid #999"> </th>
      <%= f.fields_for :line_items do |items| %>
        <%= render "line_item_fields", :f => items %>
      <% end %>
      <tr><td style="text-align: left;"><%= link_to_add_fields "Add Items", f, :line_items %></td></tr>
    </table>
    <div id ="totalinvoice" class="FR" style="padding-right: 120px;"><b style="padding-left: 5px;">Total: &nbsp;&nbsp;&nbsp;&nbsp;$&nbsp;</b><%= f.text_field :total ,:id => "invoicetotal",:size => 8, :readonly => "readonly"%></div>
    <br/>
    <div>
      <%= f.submit "Update Invoice" %>&nbsp;&nbsp;<span id="vmessage" style= "color: red;"></span>
    </div>
  <% end %>
</div>
<div style="height: 40px;"><br></br></div>

app/views/invoices/index.html.erb
<h2>INVOICE INDEX </h2>

<table class="imagetable" style="width: 95%;">
  <th style="border: 1px solid #999"><h3>ALL INVOICES</h3></th>
  <th style="border: 1px solid #999">CREATE DATE</th>
  <th style="border: 1px solid #999">DUE DATE</th>
  <th style="border: 1px solid #999">ACTIONS</th>  
  <% @invoices.each do |invoice| %>
    <tr style="border: 1px solid #999;">
      <td style="border: 1px solid #999;"><b>INV # <%= invoice.id %></b></td>
      <td style="border: 1px solid #999;"><b><%=invoice.created_at.strftime("%m/%d/%Y")%></b></td>
      <% if invoice.due_date > Time.now %>
        <td style="border: 1px solid #999;color: green;"><b><%=invoice.due_date.strftime("%m/%d/%Y")%></b></td>
      <% else %>
        <td style="border: 1px solid #999;color: red;"><b><%=invoice.due_date.strftime("%m/%d/%Y")%></b></td>
      <% end %>
      <td style="border: 1px solid #999;">
        <%= link_to image_tag("icons/eye.png"), invoice_path(:id => invoice.id) %>&nbsp;&nbsp;
        <%= link_to image_tag("icons/pencil.png"), edit_invoice_path(:id => invoice.id) %>&nbsp;&nbsp;
        <%= link_to image_tag("icons/cross.png"), invoice_path(:id => invoice.id), :confirm => 'Are you sure?', :method => 'DELETE' %>
      </td>
    </tr>
  <% end %>
</table>

app/views/invoices/new.html.erb
<h3> New Invoice </h3>
<div><br></br></div>
<div>
  <%= form_for(@invoice, :url => invoices_path) do |f| %>
    <div style="float: left; padding-left: 10px;"><b>Date: </b><%= Time.now.strftime("%m/%d/%Y")%></div>
    <div style="float: left; padding-left: 50px;"><b>Due Date: </b><%= f.text_field :due_date, :id => "datepicker2"%></div>


    <div style="padding: 10px 0 20px 0;"><br></br></div>
    <table class="imagetable" style="width:auto;">
      <th style="border: 1px solid #999"> Item </th>
      <th style="border: 1px solid #999"> Description </th>
      <th style="border: 1px solid #999"> Qty </th>
      <th style="border: 1px solid #999"> Unit Price </th>
      <th style="border: 1px solid #999"> Amount </th>
      <th style="border: 1px solid #999"> Tax Rate </th>
      <th style="border: 1px solid #999"> Amount USD </th>
      <th style="border: 1px solid #999"></th>
      <%= f.fields_for :line_items do |items| %>
        <%= render "line_item_fields", :f => items %>
      <% end %>
      <tr><td style="text-align: left;"><%= link_to_add_fields "Add Items", f, :line_items %></td></tr>
    </table>    
    <div id ="totalinvoice" class="FR" style="padding-right: 90px;"><b style="padding-left: 5px;">Total: &nbsp;&nbsp;&nbsp;&nbsp;$&nbsp;</b><%= f.text_field :total ,:id => "invoicetotal",:size => 8, :readonly => "readonly"%></div>
    <br/>
    <div>
      <%= f.submit "Create Invoice" %>&nbsp;&nbsp;<span id="vmessage" style= "color: red;"></span>
    </div>
  <% end %>
</div>
<div style="height: 40px;"><br></br></div>

app/views/invoices/show.html.erb
<div style="border: 1px solid #000; width: 950px; padding: 20px 20px 20px 20px;">
  <div id="header">INVOICE</div>
  <div>
    <div style="float: left; padding-left: 10px;"><b>Invoice # </b>INV-<%= @invoice.id%></div>
    <div style="float: right; padding-right: 10px;"><b>Date: </b><%= @invoice.created_at.strftime("%m/%d/%Y")%></div><br/>
    <div><br/></div>
    <div style="padding-left: 10px;"><b>Due Date: </b><%= @invoice.due_date.strftime("%m/%d/%Y")%></div>
    <div><br/></div>

    <table style="border: 1px solid #000; width: 100%;">
      <tr style="border: 1px solid #999;">
      <th style="border: 1px solid #999;"> Item Name</th>
      <th style="border: 1px solid #999;"> Description </th>
      <th style="border: 1px solid #999;"> Qty </th>
      <th style="border: 1px solid #999;"> Unit Price </th>
      <th style="border: 1px solid #999;"> Amount </th>
      <th style="border: 1px solid #999;"> Amount USD </th>
      </tr>
      <% @invoice.line_items.each do |c| %>
        <% @product = Product.find(c.product_id) %>
        <tr style="border: 1px solid #000;">
          <td align="center" ><%= @product.name %></td>
          <td align="center" ><%= c.description %></td>
          <td align="center" ><%= c.quantity %></td>
          <td align="center" >$<%= c.unitprice %></td>
          <td align="center" >$<%= c.amount %></td>
          <td align="center" >$<%= c.total_amount %></td>
        </tr>
        
      <% end %>
    </table>
    <br/>
    <div style="float :right; padding-right: 60px;"><b>Total- &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b>$<%= @invoice.total%></div>

  </div>
  <div><br/><br/><br/></div>
</div>

<style>
#header { height: 15px; width: 100%; margin: 20px 0; background: #222; text-align: center; color: white; font: bold 15px Helvetica, Sans-Serif; text-decoration: uppercase; letter-spacing: 20px; padding: 8px 0px; }

table { border-collapse: collapse; border: 1px solid #839E99;
background: #f1f8ee; font: .9em/1.2em Georgia, "Times New Roman", Times, serif; color: #033; }
caption { font-size: 1.3em; font-weight: bold; text-align: left; padding: 1em 4px; }
td, th { padding: 3px 3px .75em 3px; line-height: 1.3em; }
th { background: #839E99; color: #fff; font-weight: bold; text-align: center; padding-right: .5em; vertical-align: top; }
thead th { background: #2C5755; text-align: center; }
.odd td { background: #DBE6DD; }
.odd th { background: #6E8D88; }
td a, td a:link { color: #325C91; }
td a:visited { color: #466C8E; }
td a:hover, td a:focus { color: #1E4C94; }
th a, td a:active { color: #fff; }
tfoot th, tfoot td { background: #2C5755; color: #fff; }
th + td { padding-left: .5em; }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bill</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="inner_body">
      <div>&nbsp;</div>
      <div class="main_wrap">
        <div class="FR sign">
          <ul></ul>
        </div>
        <div class="FL" style="padding:5px 5px 0 0;">
          <div class="FL head_text">BILL CREATION</div>
          <div class="clear"></div>
        </div>
        <div class="FR" style="padding:5px 5px 0 0;">
          <div class="FL text">Search</div>
          <div class="FL"><input name="" type="text"  class="text_aria"/></div>
          <div class="clear"></div>
        </div>        
        <div class="clear"></div>
        <div style="height:10px"></div>
      </div>
      <div class="nav_bg">
        <div class="main_wrap">
          <div class="nab">
            <ul>
              <li style="background:none;"><%= link_to 'Home', root_url %></li>
              <li><%= link_to 'Create Invoice', new_invoice_path%></li>
              <li><%= link_to 'Create Product', new_product_path %></li>
              <li><%= link_to 'Product List', products_path %></li>
            </ul>
          </div>
        </div>
      </div>
      <% if flash[:alert] or flash[:notice] %>
        <div id="notice" <% if flash[:alert] or flash[:notice] %> class="warning"<% end %>>
          <%= flash[:alert] || flash[:notice] %>
        </div>
        <script type="text/javascript">setTimeout("$('#notice').hide();", 5000)</script>
      <% end %>
      <div class="main_wrap">
        <div style="height:8px;"></div>
        <div></div>
        <div class="body_bg" style="height:500%;overflow: hidden;padding-left: 20px;">
          <div style=" height: 20px;padding-right: 1px;"></div>
          <%= yield %>
          <div style=" height: 400px"></div>
        </div>
      </div>
    </div>
    <div class="footer">
      <div class="main_wrap">
        <div class="footer_nab">
          <ul>
            <li><a href="#">About Us</a></li>
            <li><a href="#">Carrier</a></li>
            <li><a href="#">Contact Us</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Links</a></li>
            <li>&nbsp;</li>
          </ul>
        </div>
        <div class="clear"></div>
        <p>&nbsp;</p>
      </div>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<div style="padding-left: 5px;">
  <%= form_for @product do |f| %>
    <!--<div style="color: red;"><%#= f.error_messages :header_message => " ", :message => " ", :header_tag => :h3 %></div>-->
    Product Name :<br/>
    <%= f.text_field :name%><br/>

    Product Description :<br/>
    <%= f.text_area :description, :size => "28x2"%><br/>

    Product Price :<br/>
    <%= f.text_field :price , :size => 6 %><br/>

    <%= f.submit "Submit" %>
    <br/><br/><br/><br/>
  <% end %>
</div>

app/views/products/edit.html.erb
<fieldset>
	<div class="widget first">
    	<div class="head">
    		
    	</div>
    	<%= render :partial => "form" %>
    </div>
</fieldset>

app/views/products/index.html.erb
<table cellpadding="0" cellspacing="0" width="97%" class="imagetable" id="myTable">
  <thead>
    <tr>
      <th style="width:200px;text-align:center; border: 1px solid #999">Name</th>
      <th style="width:200px;text-align:center; border: 1px solid #999">Descriptions</th>
      <th style="width:100px;text-align:center; border: 1px solid #999">Price</th>
      <th style="width:100px;text-align:center; border: 1px solid #999">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% if @products.count <= 0 %>
      <tr>
        <td colspan="6">There are currently no products</td>
      </tr>
    <% else %>
      <% @products.each do |product| %>
        <tr style="border: 1px solid #999">

          <td style="text-align:center; border: 1px solid #999"> <%= product.name %></td>
          <td style="text-align:center; border: 1px solid #999"> <%= product.description %> </td>
          <td style="text-align:center; border: 1px solid #999"> $<%= product.price %> </td>
          <td style="text-align:center; border: 1px solid #999">
            <%= link_to image_tag("icons/pencil.png"), edit_product_path(:id => product.id) %>&nbsp;&nbsp;&nbsp; <%= link_to image_tag("icons/cross.png"), product_path(:id => product.id), :confirm => 'Are you sure?', :method => 'DELETE' %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<fieldset>
  <div class="widget first">
    <div class="head">
      
    </div>
    <b>Create a New Product</b>
    <%= render :partial => "form" %>
  </div>
</fieldset>